version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rental_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentaldb
      POSTGRES_USER: rentaluser
      POSTGRES_PASSWORD: rentalpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: